apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    url: http://prometheus:9090
    isDefault: true
    access: proxy
  - name: TimescaleDB
    type: postgres
    url: timescaledb:5432
    database: pulsechain
    user: pulsechain
    secureJsonData:
      password: pulsechain_secure_pass
    jsonData:
      sslmode: disable
      timescaledb: true
    access: proxy
